language: python
dist: xenial
python:
  - "3.9"
install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt;
script:
  - flake8 . --count --exit-zero --max-complexity=16 --max-line-length=127 --statistics
  - coverage run -m pytest --ignore=lib
notifications:
  email:
    - welington.souza@mprj.mp.br
after_success:
  - codecov
